

import java.util.Scanner;
import java.awt.Frame;
import java.awt.event.WindowEvent;
import static java.awt.event.WindowEvent.WINDOW_CLOSING;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Scanner;


public class MainNotepad extends javax.swing.JFrame {
    Scanner input = new Scanner(System.in);
  
    Menu menu = new Menu();
    

    
    public MainNotepad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        metinAlani = new javax.swing.JTextArea();
        sil_buton = new javax.swing.JButton();
        kelime_bul_butonu = new javax.swing.JButton();
        cikis_buton = new javax.swing.JButton();
        yazimHatasi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        dosyaOlustur = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        kaydet = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        metinAlani.setColumns(20);
        metinAlani.setRows(5);
        metinAlani.setText("Dosya İslemleri icin Sol Ustteki File Secenegine Tiklayabilirsiniz.");
        metinAlani.setName("text"); // NOI18N
        jScrollPane1.setViewportView(metinAlani);

        sil_buton.setText("Sil (Yazılan Harfi Geri Al)");
        sil_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonActionPerformed(evt);
            }
        });

        kelime_bul_butonu.setText("Kelime Bul ve Değiştir");
        kelime_bul_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelime_bul_butonuActionPerformed(evt);
            }
        });

        cikis_buton.setText("Çıkış");
        cikis_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikis_butonActionPerformed(evt);
            }
        });

        yazimHatasi.setText("Yazım Hatası Bul ve Düzelt");
        yazimHatasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yazimHatasiActionPerformed(evt);
            }
        });

        jMenu4.setText("File");

        dosyaOlustur.setText("Dosya Oluştur(Notepadte Yazan Text İle)");
        dosyaOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaOlusturActionPerformed(evt);
            }
        });
        jMenu4.add(dosyaOlustur);

        jMenuItem1.setText("Dosya Aç");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        kaydet.setText("Kaydet");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });
        jMenu4.add(kaydet);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kelime_bul_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yazimHatasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sil_buton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(327, 327, 327)
                .addComponent(cikis_buton)
                .addGap(379, 379, 379))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kelime_bul_butonu)
                            .addComponent(cikis_buton))
                        .addGap(35, 35, 35)
                        .addComponent(yazimHatasi)
                        .addGap(41, 41, 41)
                        .addComponent(sil_buton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sil_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonActionPerformed
        
        metinAlani.setText(menu.harfSil(metinAlani.getText()));
        



    }//GEN-LAST:event_sil_butonActionPerformed

    private void kelime_bul_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelime_bul_butonuActionPerformed
        JOptionPane.showMessageDialog(null, "İsleme konsoldan devam ediniz.");
        try {
            menu.kelimeBulDegistir();
        } catch (IOException ex) {
            Logger.getLogger(MainNotepad.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_kelime_bul_butonuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "İsleme konsoldan devam ediniz.");
        try {
            menu.dosyaAc();
        } catch (IOException ex) {
            Logger.getLogger(MainNotepad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        JOptionPane.showMessageDialog(null, "İsleme konsoldan devam ediniz.");
        try {
            menu.dosyaOlustur(metinAlani.getText());           
        } catch (IOException ex) {
            Logger.getLogger(MainNotepad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kaydetActionPerformed

    private void cikis_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikis_butonActionPerformed
        JOptionPane.showMessageDialog(null, "İsleme konsoldan devam ediniz.");
        System.out.println("NotePadteki Metin Kaydedilsin mi?\n1-Evet\n2-Hayir");
        int secim=input.nextInt();
        if(secim==1){
            try {
                menu.dosyaOlustur(metinAlani.getText());
            } catch (IOException ex) {
                Logger.getLogger(MainNotepad.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Kayıt tamamlandı.");
        }
        else{
            System.out.println("Çıkış yapılıyor...");
             setVisible(false);
             dispose();
            
        }
        
        
        
       
    }//GEN-LAST:event_cikis_butonActionPerformed

    private void yazimHatasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yazimHatasiActionPerformed
        JOptionPane.showMessageDialog(null, "İsleme konsoldan devam ediniz.");
        try {
            menu.yazimHatasi();
        } catch (IOException ex) {
            Logger.getLogger(MainNotepad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yazimHatasiActionPerformed

    private void dosyaOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaOlusturActionPerformed
        JOptionPane.showMessageDialog(null, "İsleme konsoldan devam ediniz.");
        try {
            menu.dosyaOlustur(metinAlani.getText());
        } catch (IOException ex) {
            Logger.getLogger(MainNotepad.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_dosyaOlusturActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainNotepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton cikis_buton;
    private javax.swing.JMenuItem dosyaOlustur;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem kaydet;
    private javax.swing.JButton kelime_bul_butonu;
    private javax.swing.JTextArea metinAlani;
    private javax.swing.JButton sil_buton;
    private javax.swing.JButton yazimHatasi;
    // End of variables declaration//GEN-END:variables
}
